image: ubuntu:18.04

stages:
  - deploy
  - build

deploy:
  stage: deploy
  only:
    - test
  script:
    - ssh -oStrictHostKeyChecking=no $APP_SERVER "cd /home/gitlab-runner/projects/$CI_PROJECT_NAME && git checkout test && git pull origin test"

build:
  stage: build
  only:
    - test
  script:
    - ssh -oStrictHostKeyChecking=no $APP_SERVER "cd /home/gitlab-runner/projects/$CI_PROJECT_NAME && docker-compose down && docker volume prune --force && docker-compose up -d --build"
