#!/bin/bash
cd ./packets

dpkg -i ./docker/16.04/libseccomp2_2.4.1-0ubuntu0.16.04.2_amd64.deb
dpkg -i ./docker/16.04/docker-ce-cli_19.03.8_3-0_ubuntu-xenial_amd64.deb
dpkg -i ./docker/16.04/containerd.io_1.2.13-1_amd64.deb
dpkg -i ./docker/16.04/docker-ce_19.03.8_3-0_ubuntu-xenial_amd64.deb

systemctl enable docker
systemctl start docker

cp ./docker/16.04/docker-compose /usr/local/bin/
chmod +x /usr/local/bin/docker-compose
