#!/bin/bash
cd ./packets

dpkg -i ./docker/18.04/docker-ce-cli_19.03.12_3-0_ubuntu-bionic_amd64.deb
dpkg -i ./docker/18.04/containerd.io_1.2.13-2_amd64.deb
dpkg -i ./docker/18.04/docker-ce_19.03.12_3-0_ubuntu-bionic_amd64.deb

systemctl enable docker
systemctl start docker

cp ./docker/18.04/docker-compose /usr/local/bin/
chmod +x /usr/local/bin/docker-compose
